name: release

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install GitVersion
        uses: gittools/use-gitversion/setup@v0.2
        with:
          versionSpec: "5.1.x"

      - name: Use GitVersion
        id: gitversion
        uses: gittools/use-gitversion/execute@v0.2
      - run: |
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.0
        with:
          files: downleth/__init__.py
        env:
          GitVersion: ${{ steps.gitversion.outputs.majorMinorPatch }}

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: "Install downleth"
        run: python setup.py install

      - name: Publish Docker
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
          docker image build -t thomasgassmann/downleth:latest -t thomasgassmann/downleth:${{ steps.gitversion.outputs.majorMinorPatch }} .
          docker push thomasgassmann/downleth:latest
          docker push thomasgassmann/downleth:${{ steps.gitversion.outputs.majorMinorPatch }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
